stages:
  clean_metadata:
    cmd: python3 src/clean_metadata.py
        --input_bucket 697-datasets
        --input_file meta_Electronics-0.1-percent.csv
        --output_file data/cleaned_output.csv
    outs:
    - data/cleaned_output.csv
  train_lda:
    cmd: python3 src/train_lda.py
        --input_file data/cleaned_output.csv
        --output_model models/lda_model.joblib